### ISSUE TITLE
Out of date

### ISSUE THREAD

**Issue by Yama-K** [fakundo/tarkov-raid-items#1]
Title says it, neat tool, really useful. Any plans to update this?

**Comment by fakundo** [comment]
Hey! Can you provide an example of something outdated?
I'm parsing data from this page -- https://escapefromtarkov.fandom.com/wiki/Found_in_raid
and it seems pretty fine to me.

**Comment by Yama-K** [comment]
Hey! My bad, or more of a friends bad, he checked the website out and thought things were missing but apparently are not now. Thanks for this tool though, hella useful!

**Comment by Yama-K** [comment]
Actually I have to go back on my word. SJ1's are required in Assessment - Part 3, same with SJ9 and SJ6.

**Comment by fakundo** [comment]
Alright I'll take a look. Thanks!
